### ISSUE TITLE
error compiling rtorrent with the current git ("feature-bind")

### ISSUE THREAD

**Issue by ayukas** [rakshasa/rtorrent#536]
compile with gcc 5.4.1 on Ubuntu 12.04.5

> ...
In file included from command_download.cc:45:0:
../rak/socket_address.h: In member function ‘std::string rak::socket_address_ine           t6::pretty_address_str() const’:
**../rak/socket_address.h:520:37: error: expected ‘)’ before ‘PRIu16’
     if (snprintf(last_char, 7, ":%" PRIu16, port()) == -1)**
../rak/socket_address.h:520:51: warning: spurious trailing ‘%’ in format [-Wform           at=]
     if (snprintf(last_char, 7, ":%" PRIu16, port()) == -1)
...

> 

any ideas?

**Comment by jungle-boogie** [comment]
Did you compile this branch:
https://github.com/rakshasa/libtorrent/tree/feature-bind

**Comment by ayukas** [comment]
Yeah exactly as the title described, I have had the #527 issue first when compile from the master branch.
After then I pull the "feature-bind" branch got that covered and met this new error.

**Comment by rakshasa** [comment]
Fixed usage of <inttypes.h> with <cstdint> and <cinttypes> as needed.

**Comment by jungle-boogie** [comment]
@rakshasa,

Looks like builds are failing:
https://github.com/rakshasa/rtorrent/commits/feature-bind

@ayukas,

I pointed you to the feature-bind of libtorrent, not rtorrent.

**Comment by rakshasa** [comment]
It's an issue with the latest g++-4.8 build in ubuntu's ubuntu-toolchain-r-test handling of templates.

https://travis-ci.org/rakshasa/rtorrent
