### ISSUE TITLE
make failing using micdu release

### ISSUE THREAD

**Issue by jxer** [rakshasa/rtorrent#364]
failing make using Micdu70/master 

command_download.cc:870:3:   required from here
rpc/command.h:193:79: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
mv -f .deps/command_file.Tpo .deps/command_file.Po
mv -f .deps/command_ip.Tpo .deps/command_ip.Po
mv -f .deps/command_dynamic.Tpo .deps/command_dynamic.Po
mv -f .deps/command_groups.Tpo .deps/command_groups.Po
mv -f .deps/command_local.Tpo .deps/command_local.Po
mv -f .deps/command_download.Tpo .deps/command_download.Po
make[3]: Leaving directory '/home/jxer/home/files/rtorrent-master/src'
Makefile:601: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src'
Makefile:437: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/jxer/home/files/rtorrent-master'
Makefile:368: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by jxer** [comment]
make[3]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/utils'
make[3]: Entering directory '/home/jxer/home/files/rtorrent-master/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_download.o -MD -MP -MF .deps/command_download.Tpo -c -o command_download.o command_download.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_dynamic.o -MD -MP -MF .deps/command_dynamic.Tpo -c -o command_dynamic.o command_dynamic.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_events.o -MD -MP -MF .deps/command_events.Tpo -c -o command_events.o command_events.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_file.o -MD -MP -MF .deps/command_file.Tpo -c -o command_file.o command_file.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_ip.o -MD -MP -MF .deps/command_ip.Tpo -c -o command_ip.o command_ip.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_helpers.o -MD -MP -MF .deps/command_helpers.Tpo -c -o command_helpers.o command_helpers.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_groups.o -MD -MP -MF .deps/command_groups.Tpo -c -o command_groups.o command_groups.cc
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_local.o -MD -MP -MF .deps/command_local.Tpo -c -o command_local.o command_local.cc
command_events.cc:48:44: fatal error: torrent/utils/directory_events.h: No such file or directory
 #include <torrent/utils/directory_events.h>

**Comment by jxer** [comment]
make check
Making check in doc
make[1]: Entering directory '/home/jxer/home/files/rtorrent-master/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/jxer/home/files/rtorrent-master/doc'
Making check in src
make[1]: Entering directory '/home/jxer/home/files/rtorrent-master/src'
Making check in core
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/core'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/core'
Making check in display
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/display'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/display'
Making check in input
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/input'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/input'
Making check in rpc
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/rpc'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/rpc'
Making check in ui
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/ui'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/ui'
Making check in utils
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src/utils'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src/utils'
make[2]: Entering directory '/home/jxer/home/files/rtorrent-master/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I. -I..   -g -O2 -g -DDEBUG -Wall -std=c++11 -pthread   -I/usr/local/include  -I/usr/local/include  -MT command_events.o -MD -MP -MF .deps/command_events.Tpo -c -o command_events.o command_events.cc
command_events.cc:48:44: fatal error: torrent/utils/directory_events.h: No such file or directory
 #include <torrent/utils/directory_events.h>
                                            ^
compilation terminated.
Makefile:568: recipe for target 'command_events.o' failed
make[2]: *** [command_events.o] Error 1
make[2]: Leaving directory '/home/jxer/home/files/rtorrent-master/src'
Makefile:601: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/jxer/home/files/rtorrent-master/src'
Makefile:437: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by Micdu70** [comment]
Yeap... something wrong happened but I don't understand what/why...

I just created a new repo for rtorrent here... (should works) => https://github.com/Micdu70/rtorrent-fix

**Comment by jxer** [comment]
fixed, Thank you, only took me 3 hours to post, but its fully working now!

on a side note  i did notice its not working with libtorrent 1.07, had to use 13.6, not sure if your aware

**Comment by Micdu70** [comment]
rtorrent uses libtorrent (rakshasa), not libtorrent (rasterbar). It's two different libraries. ;)

**Comment by jxer** [comment]
lol that prolly is the issue huh? :) thanks again
