### ISSUE TITLE
can't build on ubuntu 18.04

### ISSUE THREAD

**Issue by chovy** [rakshasa/rtorrent#769]
When I do `sudo make install` I get this:

```
In file included from diffie_hellman.cc:43:0:
diffie_hellman.cc: In member function ‘void torrent::DiffieHellman::store_pub_key(unsigned char*, unsigned int)’:
diffie_hellman.cc:106:39: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
   if ((int)length >= BN_num_bytes(m_dh->pub_key))
                                       ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from diffie_hellman.cc:43:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
diffie_hellman.cc:107:19: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
     BN_bn2bin(m_dh->pub_key, dest + length - BN_num_bytes(m_dh->pub_key));
                   ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from diffie_hellman.cc:43:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
In file included from diffie_hellman.cc:43:0:
diffie_hellman.cc:107:63: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
     BN_bn2bin(m_dh->pub_key, dest + length - BN_num_bytes(m_dh->pub_key));
                                                               ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from diffie_hellman.cc:43:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
Makefile:422: recipe for target 'diffie_hellman.lo' failed
make[2]: *** [diffie_hellman.lo] Error 1
make[2]: Leaving directory '/home/username/src/install/libtorrent-0.13.7/src/utils'
Makefile:573: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/username/src/install/libtorrent-0.13.7/src'
Makefile:503: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```
