### ISSUE TITLE
rTorrent fails to build with clang

### ISSUE THREAD

**Issue by gardnermj** [rakshasa/rtorrent#14]
rTorrent 0.9.0 fails to build with clang on Mac OS X 10.7:

```
/Developer/usr/bin/clang++ -DHAVE_CONFIG_H -I. -I../.. -I. -I./.. -I../..  -I/opt/local/include  -pipe -O2 -arch x86_64 -DNDEBUG -I/opt/local/include/sigc++-2.0 -I/opt/local/lib/sigc++-2.0/include   -I/opt/local/include   -I/opt/local/include   -MT window_http_queue.o -MD -MP -MF .deps/window_http_queue.Tpo -c -o window_http_queue.o window_http_queue.cc
window_file_list.cc:126:19: error: variable length array of non-POD element type 'iterator' (aka 'torrent::FileListIterator')
  iterator entries[m_canvas->height() - 1];
                  ^
1 error generated.
```
